### PR TITLE
Style updates to the ARM Tentacle blog post

### PR DESCRIPTION
**Pull request by kathrynmarks**
I've proposed some minor changes to align this post with our style guide.

Since this may give you food for thought, I figured it best to raise this for your review rather than apply changes directly to main.

### CODE REVIEW

**Comment by TeganAli** [comment]
@leecarlon I assume Kathryn's edits are correct but can you please confirm, as I still get this wrong sometimes? Thanks

**Comment by wordlee** [comment]
Thanks Tegan and Kathryn. Tentacle should always be capitalized, as should Listening and Polling Tentacle(s). The other corrections are correct though.

**Comment by TeganAli** [comment]
@kathrynmarks are you happy to update this based on Lee's feedback? Thanks so much :)

**Comment by kathrynmarks** [comment]
@TeganAli, yep, can do!

**Comment by kathrynmarks** [comment]
I've reverted all changes to instances of `Tentacle`, including `Polling Tentacle`. Should be good to go now, @TeganAli.

Thanks to both of you for your help; I've noted the style rule for Tentacle.

**Pull request merged**
