### PR TITLE
Initial draft for adding structured variables to k8s yaml

### PR DESCRIPTION
**Pull request by zentron**
# About

This is a post about a quality-of-life feature that added to support supporting structured variables with kubernetes yaml steps

# Release

Is this post for a specific release? If so which one?: **TBD. Will confirm and update before post goes live**

# Blog image idea

The design team will work on a design for the blog image. Add any ideas you have about the graphic image here.
**🤔 Something do do with yaml and updating specific values... maybe octopus with a magnifying glass over the file or something?**

# Pre-requisites

- [ ] The draft is complete and this post is ready to be reviewed. - **Note: Still awaiting confirmation of version**
- [ ] I'm familiar with the [writing for Octopus TL;DR](https://www.octopus.design/writing/writing-tldr/). **Note: broken link? Presuamly should be [here](https://www.octopus.design/932c0f1a9/p/26f741-writing)?**
- [x] The PR build passes validation, and if it doesn't, I've checked the [common validations errors](https://style.octopus.com/writing-at-octopus-tldr#common-validation-errors) and none of those apply.
- [x] The images I've included follow the [rules for working with images](https://www.octopus.design/writing/working-with-images/).
- [x] I've added alt text for all the images I've included (alt text describes image to people unable to see it, 125 characters max)
- [ ] One screenshot (if any are included) is suitable for Twitter. This screenshot should be 16:9 ratio and at least 1200 x 675 pixels. For screenshots from the Octopus Web Portal, please use Chrome and the browser’s zoom function to remove as much white space as possible. If screenshots are annotated (e.g., with boxes or arrows), please also provide a version that is unannotated for use on Twitter. Do not use dark mode for the Octopus Web Portal.

### CODE REVIEW

**Comment by TeganAli** [comment]
@zentron and @nikita-dergilev, is this feature tied to the 2023.1 release? Thanks.

**Comment by nikita-dergilev** [comment]
> @zentron and @nikita-dergilev, is this feature tied to the 2023.1 release? Thanks.

It's already merged, so it should be in 2023.1. However, it will be available in the cloud earlier.

FYI @zentron

**Comment by TeganAli** [comment]
Thanks @nikita-dergilev. Are you and @zentron happy with all the edits to this post and the mention of 2023.1? I need to publish it tomorrow so I have the link for the newsletter. Thank you!

**Comment by zentron** [comment]
Looks good. Thanks for the proof read and restructure @TeganAli

**Comment by TeganAli** [comment]
Great, thanks so much, @zentron :)

**Comment by nikita-dergilev** [comment]
Fantastic, many thanks, @zentron and @TeganAli! The post looks good to me.

**Comment by TeganAli** [comment]
Awesome, thanks, @nikita-dergilev.

**Review by TeganAli — APPROVED** [review]

**Pull request merged**
