### PR TITLE
SQL Server and PowerShell made easier with dbatools: Practical Examples

### PR DESCRIPTION
**Pull request by Alex-Yates**
New blog post for publication in June.

### CODE REVIEW

**Comment by wordlee** [comment]
Hi Alex, great post.

> Line 46: Surely the quote should come before the full stop? Since I'm only quoting a part of a sentence within the context of my own sentence?

Yeah, I originally added in a comma after `that` before the opening quotation mark and added the full stop. I should have put the full stop back when I removed the comma :) I'll do it now. 

> Line 84: "do the heavy lifting" is a direct quote from James' post, so wouldn't it be better to use quotes than *s?

I thought that was commentary, I'll add the quotes back in.
 
> Lines 128 and 129: The blog posts I'm referencing both start with lower case letters. I think it's better to be true to the posts I'm referencing than to correct their Grammer, since I'm afraid that looks dismissive or snobby. They've chosen to use all lower case for their own style reasons and I'd prefer to respect that when quoting them.

Autopilot/muscle memory on that, no dismissiveness intended. When I add links to posts, I just copy the link twice and delete the `-` and add capitals where appropriate. I'll change them back 
 
> Otherwise, all looks good to me. Thanks for the edit!

Thanks for the post, and commenting on the edits. I was planning to leave comments, but got called away. I was planning to keep the link to the public repo in the post, but copy the gists into the post to future proof the post. I'll do that when I make the above corrections.

**Comment by Alex-Yates** [comment]
Cool.

Is it not better to embed the code. That way if it ever needs updating, perhaps because dbatools changes their syntax or a reader suggests an improvement, it can be done in one place rather than two?

**Comment by wordlee** [comment]
I'm not sure they'll format as code blocks on the blog, which is my main concern.

Do you maintain these as a reference independent of this post?

**Comment by Alex-Yates** [comment]
I tested the embed link on my own WordPress site and it worked ok.

The code is available on GitHub, and the repo is referenced somewhere near
the start of the blog post.

We do have a dependency on the tool I'm using to convert code from a
regular repo into a gist. Under normal circumstances I would have just used
gists, but I wanted to match James' style as much as possible. Hence using
the external tool for making the scripts feel like gists.

**Comment by wordlee** [comment]
Cool. I'll test them on the blog and see how we go (I can copy one into a private post and check the results before we publish the post). I'll let you know.

**Comment by wordlee** [comment]
FYI: Rob tested the post, and unfortunately, the code samples didn't show up at all:

Screen Shot 2020-06-04 at 12 48 44

No doubt something to do with our blog engine, but I'll copy the samples in.

**Pull request merged**
