### PR TITLE
May blog post: Runbooks and SQL Clone

### PR DESCRIPTION
**Pull request by Alex-Yates**

### CODE REVIEW

**Comment by Alex-Yates** [comment]
Not sure if I got the navigation links right, but I'm sure you know how the syntax is supposed to work. My intention was for the three bullets in the tl;dr to link to the three main headers of the post.

**Comment by wordlee** [comment]
> Not sure if I got the navigation links right, but I'm sure you know how the syntax is supposed to work. My intention was for the three bullets in the tl;dr to link to the three main headers of the post.

What you have works, but because you're linking within a single doc you don't need to include the file path, just the anchor, for instance [Why this is important](#why). I'll update it as I got through the post.

**Comment by wordlee** [comment]
Yep. You're right. I do forget that people say "sequel" and an sequel doesn't make sense :) I'll drop the n's.

**Comment by Alex-Yates** [comment]
👍

**Comment by Alex-Yates** [comment]
Otherwise all looks good.

Although I was a bit confused by the commas after etc and e.g. in your
second pass.

But I'll take your word on it. You're the wordsmith! 🤣

Alex

**Comment by wordlee** [comment]
e.g., is weird. I trusted Grammarly on that one :) I just looked it up, and e.g. is "typically followed by a comma in US English but not in other English speaking countries 🤷‍♂️

**Comment by Alex-Yates** [comment]
Just had a thought. I don't think I call out anywhere that the tools mentions are specifically for SQL Server databases. Do you think that's important?

**Comment by robpearson** [comment]
@Alex-Yates Nah, I think it's implied. I did a quick search and SQL Server appears a bunch of time throughout so I think it's all good. 👍 Also, the core concepts discussed can be applied to any other database with similar tooling so it's broadly useful too.

**Comment by Alex-Yates** [comment]
Cool, all good then!

**Pull request merged**
